@startuml

scale 1.4
skinparam titleFontSize 10

object "Dosage" as dosage {
  [[http://hl7.org/fhir/StructureDefinition/Dosage Dosage (basic)]]
}

object "Normal Dosing" as dosagenormal {
  IHE PHARM 1.3.6.1.4.1.19376.1.5.3.1.4.7.1
  [[StructureDefinition-ch-emed-dosage-normal.html CH EMED Dosage Normal]]
}
object "Structured" as dosagenormalstructured {
  IHE PHARM 1.3.6.1.4.1.19376.1.5.3.1.4.7.1
}
object "Narrative" as dosagenormalnarrative {
  IHE PHARM 1.3.6.1.4.1.19376.1.5.3.1.4.7.1
}

object "Split Dosing" as dosagesplit {
  IHE PHARM 1.3.6.1.4.1.19376.1.5.3.1.4.9
  [[StructureDefinition-ch-emed-dosage-split.html CH EMED Dosage Split]]
}


dosage <|-- dosagenormal
dosagenormal <|-- dosagenormalstructured
dosagenormal <|-- dosagenormalnarrative
dosage <|-- dosagesplit
@enduml